bus_time/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views as btv
from main import views as main_views

app_name = "bus_time"

urlpatterns = [
    path('search/', btv.SearchResult.as_view(), name='search'),
    path('search_input/', btv.SearchInput.as_view(), name='search_input'),
    path('bus_stops/<slug:ext_id>', btv.bus_stop_detail, name='bus_stops'),
    path('timezone/', btv.set_time, name='set_tz'),
    # path('set_timezone/', btv.set_timezone, name='set_timezone'),
    path('streets/<slug:street_slug>/', btv.street_detail, name='street_detail'),
    path('routes/<slug:id_route>/', btv.route_detail, name='route_detail'),
    # path('timezone/', btv.set_timezone, name='timezone'),
    path('', main_views.index, name='index'),
]

woodbus/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path

from main.views import (ContributorView, TermsAndCondsView, TranslationView,
        WIPPageView)


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('auth/', include('hash_email_auth.urls')),
    path('contributors/', ContributorView.as_view(), name='contributors'),
    path('translations/', TranslationView.as_view(), name='translations'),
    path('terms_and_conds/', TermsAndCondsView.as_view(),
            name='terms_and_conds'),
    path('wip/', WIPPageView.as_view(), name='wip'),
    path('', include('bus_time.urls')),
    prefix_default_language=False,
)

bus_time/models.py
import pytz

from collections import OrderedDict
from datetime import datetime, timedelta # datetime: class

# https://stackoverflow.com/questions/4631865/caching-query-results-in-django
from django.core.cache import cache
from django.db import models
from django.conf import settings
#from django.urls import reverse
from django.utils import timezone
#from django.utils.text import slugify
from django.utils.translation import gettext as _
#from unidecode import unidecode

from cities_light.models import City


FORWARD = 'Di' # FW
RETURN = 'Ve' # BW
DIRECTION = (
    (FORWARD, _('Forward')),
    (RETURN, _('Return')),
)


def make_cache_key(sor, time):
    time = str(time).replace(" ", "-")
    key = 'sor_{0}_{1}'.format(str(sor.pk), time)
    return key

def calc_eta(time, minutes):
    now = timezone.now()
    return datetime.combine(now, time, now.tzinfo) + timedelta(minutes=minutes)


def search(for_text):
    '''
    Search for_text in applicable models then return list of matched objects.

    # This is just one of possible solutions. Please propose another one.
    return [
            {
                'model': 'Street',
                'found': ['city - street name', 'city - street name'...]
                }...
            ]
    '''
    if for_text.strip() == "":
        streets = None
        routes = None
        message = 'Cần nhập tiêu chí tìm kiếm khác rỗng'
    #print('BusRoute:', BusRoute.objects.all())
    else:
        streets = Street.objects.filter(name__contains=for_text.strip())
        busstops = BusStop.objects.filter(street__in=streets)
        routes = BusRoute.objects.filter(models.Q(bus_stop__in=busstops)
                | models.Q(name__contains=for_text.strip())).distinct()
        #print(routes.query)
        message = None
        if routes.count() == 0:
            message = 'Không tìm thấy kết quả'
        else: pass
        #print(routes)
        #print(routes.query)
    return OrderedDict({
            'Street': streets,
            'BusRoute': routes,
            'message': message
            })


class StrPKAbstractModel(models.Model):
    class Meta:
        abstract = True

    def __str__(self):
        return '{0}: {1}'.format(self.pk, self.describe())


class NameAbstractModel(StrPKAbstractModel):
    name = models.CharField('Name', max_length=200)

    class Meta:
        abstract = True

    def describe(self):
        return self.name


class ExternalIdModel(StrPKAbstractModel):
    external_id = models.CharField(max_length=20, blank=True, null=True,
            unique=True)

    class Meta:
        abstract = True

    def get_second_id(self):
        text, num = self.external_id.split('_')
        return num

    def get_third_id(self):
        text, text2, num = self.external_id.split('_', 2)
        return num

    def describe(self): # pragma: no cover
        return self.external_id


class Passenger(models.Model):
    full_name = models.CharField('Full name', max_length=200)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name='User',
            on_delete=models.CASCADE,)
    balance = models.FloatField('Balance', default=0)

    class Meta:
        verbose_name = 'Passenger'
        verbose_name_plural = 'Passengers'


class Street(NameAbstractModel, ExternalIdModel):
    ''' each city has list of streets'''
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    #slug: city name+street name, unique,
    # TODO: change when street name or city change
    slug = models.SlugField(max_length=200)

    class Meta:
        verbose_name = 'Street'
        verbose_name_plural = 'Streets'

    def __str__(self):
        return self.city.name + ' - ' + self.name

    def get_bus_stops(self, is_even):
        ''' Return list of bus stops on routes filtered by side. '''
        stops = self.busstop_set.filter(even=is_even)
        return stops

    #def get_sequenced_streets(self):
    #    '''
    #    Return list of bus stops on previous and next streets group by route.
    #    '''

    #def get_sors_of_direction(self, direction):
    #    stops = self.busstop_set.all()
    #    sors = StopOnRoute.objects.filter(
    #            bus_stop__in=stops).order_by('bus_route')
    #    # TODO: check which scenario that has different directions
    #    sors_direction = sors.filter(direction=direction)
    #    return sors_direction

    def get_sors_on_other_street(self, list_sors, offset=0,
            first=False, last=False):
        sor_pre = [sor.get_stop(offset, first=first, last=last)
                for sor in list_sors]
                #for sor in list_sors
                # if sor is not null
        sors = [sor for sor in sor_pre if sor and sor.bus_stop.street != self]
        return sor_pre if first or last else sors


class Transaction(NameAbstractModel):
    passenger = models.ForeignKey(Passenger, verbose_name='Passenger',
            on_delete=models.CASCADE)
    date = models.DateField('Date')
    category = models.CharField('Category', max_length=200)
    amount = models.FloatField('Amount')

    class Meta:
        verbose_name = 'Transaction'
        verbose_name_plural = 'Transactions'


class Duration(ExternalIdModel):
    start_time = models.TimeField('Start time')
    minutes = models.IntegerField('Minutes')

    class Meta:
        verbose_name = 'Duration'
        verbose_name_plural = 'Durations'


cache_stat = {
        'cache_hit': 0,
        'cache_missed': 0,
        }

class BusStop(NameAbstractModel, ExternalIdModel):
    ''' each street has list of bus stops'''
    street = models.ForeignKey(Street, verbose_name='Street',
            on_delete=models.CASCADE)
    even = models.BooleanField('Even')
    order = models.IntegerField('Order', blank=True, null=True)
    latitude = models.FloatField('Latitude', default=0)
    longitute = models.FloatField('Longitute', default=0)

    class Meta:
        verbose_name = 'Bus Stop'
        verbose_name_plural = 'Bus Stops'

    def get_routes_with_buses_and_eta(self, at_time, num_list):
        # print('at_time_models', at_time)
        list_buses_estm = []
        for sor in self.stoponroute_set.all():
            buses_of_sor = []
            cached_buses = cache.get(make_cache_key(sor, at_time))
            if cached_buses:
                #print('4. Exist, Get from cache 1 bus with 5 eta:')
                cache_stat['cache_hit'] += 1
                #print('cache_hit', cache_stat['cache_hit'])
                list_buses_estm.extend(cached_buses[:num_list])
                continue
            else: pass

            #print('1. Not exist: from sor, calculate 1 bus with 5 eta: done')
            cache_stat['cache_missed'] += 1
            buses_not_reached_bus_stop = self.get_buses_not_reached_bus_stop(
                    at_time, sor)
            #print('buses_not_reached_bus_stop', buses_not_reached_bus_stop)
            num_buses = 5 - len(buses_not_reached_bus_stop)
            sum_minute = sor.get_sum_all_average_time()
            buses_not_start = Bus.get_buses_not_start(at_time, sum_minute,
                        sor, num_buses)
            #print('sum_time_view',  sor.bus_route.pk, sor.direction, sum_minute)
            buses_of_sor.extend(buses_not_reached_bus_stop)
            buses_of_sor.extend(buses_not_start)
            list_buses_estm.extend(buses_of_sor[:num_list])
            #print('2. Saved 1 bus with 5 eta to cache:')
            eta_of_bus_before_first_bus = at_time #'WIP'
            cached_buses = cache.set(make_cache_key(sor,
                eta_of_bus_before_first_bus), buses_of_sor)
        #print('cache_missed',  cache_stat['cache_missed'])
        return list_buses_estm

    def get_buses_not_reached_bus_stop(self, at_time, sor):
        sob_not_in_sob_of_bus_stop = self.stopofbus_set.filter(
                bus__direction=sor.direction,
                arrived_time__lt=at_time, bus__bus_route=sor.bus_route)

        # Option 1
        arrived_sobs = StopOfBus.objects.filter(arrived_time__lt=at_time,
                bus__bus_route=sor.bus_route, bus__direction=sor.direction)
        buses_in_sob_arrived = Bus.objects.filter(
                stopofbus__in=arrived_sobs).distinct()
        #print('buses_sob_arr', buses_in_sob_arrived)
        list_buses = buses_in_sob_arrived.exclude(
                stopofbus__in=sob_not_in_sob_of_bus_stop)

        # Option 2
        #self_arrived_sobs = self.stopofbus_set.filter(arrived_time__lt=at_time,
        #        bus__bus_route=bus_route, bus__direction=direction)
        #arrived_buses = [sob.bus for sob in self_arrived_sobs]
        #arrived_sobs_before_self = StopOfBus.objects.filter(
        #        arrived_time__lt=at_time, bus__in=bus_route.bus_set.all(),
        #        bus__bus_route=bus_route, bus__direction=direction,
        #        ).exclude(bus__in=arrived_buses)
        #new_buses = Bus.objects.filter(pk__in=set(sob.bus.pk
        #        for sob in arrived_sobs_before_self))
        #print('get_buses_not_reached_bus_stop', #arrived_buses,
        #        #arrived_sobs_before_self,
        #        new_buses, sep='\n')
        buses = [(bus, sor.get_estimated_time(bus, at_time))
                for bus in list_buses
                if sor.get_estimated_time(bus, at_time) >= at_time]
        #print('buses', buses)
        return buses

    #def long_name(self):
    #    return '{0} ({1}) {2}'.format(
    #            self.street, 'Even' if self.even else 'Odd', self.name)

    def describe(self):
        return '{0} {1} {2}'.format(
                self.street, 'Even' if self.even else 'Odd', self.name)


class BusCompany(NameAbstractModel, ExternalIdModel):
    ''' Each city has list of operating bus companies'''
    phone_number = models.CharField('Phone number', max_length=200)

    class Meta:
        verbose_name = 'Bus Company'
        verbose_name_plural = 'Bus Companies'


class BusRoute(NameAbstractModel, ExternalIdModel):

bus_time/templates/bus_time/bus_route.html
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}
</style>
<h1 style="color: white">{{ bus_route.name  }}</h1>
<p style="color:white">Giá vé lượt <strong>{{ bus_route.price }}</strong>đ</p>
<input type="hidden" id="object_with_id" name="object_with_id" value="bus_route-{{ bus_route.external_id }}">
<table style="background-color:#88ffaa;" border="1">
  {% include "bus_time/generic_route.html" with direction_display='Forward' buses=forward_buses sors=forward_sors sobs=forward_sobs eta_list=forward_eta_list %}
</table>
<table style="background-color:#ffaa88;" border="1">
  {% include "bus_time/generic_route.html" with direction_display='Return' buses=return_buses sors=return_sors sobs=return_sobs eta_list=return_eta_list %}
</table>

bus_time/templates/bus_time/bus_stop.html
{% load i18n %}
<style scoped="">
    .tram {
        margin:10px;padding:20px;border:1px solid;
        background-color:rgba(255,255,255,0.7);
    }
    .ic-transitioning #Mh_Tram {
      background: darkseagreen;
    }
    #Mh_Tram {
      transition: all 3.0s;
    }
</style>
<div class="w3-container w3-cell-row" id="Mh_Tram" ic-sse-src="">
  <div class="w3-col m2 l3">&nbsp;</div>
  <div class="w3-col m8 l6 tram">
    <h3 class="w3-text-blue">🚏&nbsp;Trạm&nbsp;{{ bus_stop.name }}</h3>
    {# bus_time/templates/bus_time/generic_button.html #}
    {% url 'bus_time:street_detail' bus_stop.street.slug as get_from %}
    {% include "bus_time/generic_button.html" with get_from=get_from content=bus_stop.street.name cls_type='street' target='page_content' %}
    <br/>
    {% for route, sor in route_sor %}
    {% url 'bus_time:route_detail' route.external_id as get_from %}
    {% include "bus_time/generic_button.html" with get_from=get_from content=route.external_id cls_type='route' target='page_content' %}
    <span class="w3-xlarge w3-text-blue">
      {{ route.name }}
      <strong>{% trans sor.get_direction_display %}</strong>
    </span>
    <br/>
    {% for bus, time_ in bus_estm %}
    {% if bus.bus_route == route and bus.direction == sor.direction  %}
      {# Similar to bus_time/generic_street.html #}<span style="color: blue">🚍&nbsp;{{ bus.get_third_id }}:&nbsp;<strong>⌛&nbsp;{{ time_|time:"H:i" }}</strong>;</span>
    {% endif %}
    {% endfor %}
    </br>
    {% endfor %}
  </div>
</div>

bus_time/templates/bus_time/generic_button.html
<button class="btn btn-info info-{{ cls_type }}"
    ic-get-from="{{ get_from }}"
    ic-target="#{{ target }}">{{ emoji }}{{ content }}</button>

bus_time/templates/bus_time/generic_route.html
{% load i18n %}
<thead>
  <tr>
    <th>{% trans "Route direction" %} {% trans direction_display %}</th><th>{% trans 'Bus stop' %}</th>
    {% for bus in buses %}
    <th>{{ bus.get_third_id }}</th>
    {% endfor %}
  </tr>
</thead>
<tbody>
  {% for sor, rowspan in sors %}
  <tr>
    {% ifchanged sor.bus_stop.street %}
    <td id="" rowspan="{{ rowspan }}" style="width:100px">
      {% url 'bus_time:street_detail' sor.bus_stop.street.slug as get_from %}
      {% include "bus_time/generic_button.html" with cls_type='street' get_from=get_from target='page_content' content=sor.bus_stop.street.name %}
    </td>{% endifchanged %}
    <td>
      {% url 'bus_time:bus_stops' sor.bus_stop.external_id as get_from %}
      {% include "bus_time/generic_button.html" with cls_type='busstop' get_from=get_from target='page_content' content=sor.bus_stop.name %}</td>
    {% for sob in sobs %}
    {% if sob.bus_stop == sor.bus_stop %}
    <td><span style="color: #888888">{{ sob.arrived_time|time:"H:i" }}</span></td>
    {% endif %}
    {% endfor %}
    {% for eta_sor, eta in eta_list %}
    {% if eta_sor.bus_stop == sor.bus_stop %}
    <td><span>{{ eta|time:"H:i" }}</span></td>
    {% endif %}
    {% endfor %}
  </tr>
  {% endfor %}
</tbody>

bus_time/templates/bus_time/generic_street.html
{% load i18n %}
{% for stop, bus_time in stops %}
<div class="w3-cell" style="width:13%; padding: 5px">
<div class="w3-card-4 w3-light-gray" style="border-radius: 10px">
  <div class="w3-row">
    {% url 'bus_time:bus_stops' stop.external_id as get_from %}
    {% include "bus_time/generic_button.html" with get_from=get_from emoji="🚏" content=stop.name cls_type='busstop w3-text-indigo' target='details' %}
  </div>
    {% for route in stop.busroute_set.all %}
    {% ifchanged route.get_second_id %}
  <div class="w3-row">
    <div class="w3-col l3 w3-center">
      {% url 'bus_time:route_detail' route.external_id as get_from %}
      {% include "bus_time/generic_button.html" with get_from=get_from content=route.get_second_id cls_type='route' target='page_content' %}</br>
    </div>
    {% for bus, eta in bus_time %}
    {% if bus.bus_route.get_second_id == route.get_second_id %}
    <div class="w3-col l9 w3-center">
      {# Similar to bus_time/bus_stop.html #}<span style="color: blue">🚍&nbsp;{{ bus.get_third_id }}:<strong>⌛&nbsp;{{ eta|time:"H:i" }}</strong>;</span>
    </div>
    {% endif %}
    {% endfor %}
  </div>
  {% endifchanged %}
  {% endfor %}
</div>
</div>
{% endfor %}

bus_time/templates/bus_time/search_input.html
{% load i18n %}
{% load tz %}
{% get_current_timezone as TIME_ZONE %}
<div class="w3-left" style="margin-top: 5px">
  <input class="w3-border" type="text" id="th_chuoi_tim_kiem"
                              name="q" value="{{ search_text }}"
                              placeholder="Nhập vào đây để tìm..."
                              ic-get-from="{% url 'bus_time:search' %}"
                              ic-taget="page_content"
                              ic-trigger-on="keyup changed" ic-trigger-delay="500ms"
                              ic-target="#page_content">

  <input class="w3-border" id="at_time" name="at_time" style="width: 90px"
                        placeholder="{% trans 'HH:MM' %}"
                        pattern="([01]*[0-9]|2[0-3]):[0-5]*[0-9]"
                        required
                        value="{{ at_time }}"
                        ic-get-from="{% url 'bus_time:set_tz' %}"
                        ic-include="#object_with_id"
                        ic-target="#page_content">

  <label for="timezone">Time zone:</label>
  <input list="timezones" name="timezone" id="timezone" value="{{ TIME_ZONE }}"
                    ic-get-from="{% url 'bus_time:set_tz' %}"
                    ic-include="#object_with_id"
                    ic-target="#page_content">
  <datalist id="timezones">
      {% for tz in timezones %}
      <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
      {% endfor %}
  </datalist>
</div>

bus_time/templates/bus_time/search_result.html
<style>
#message{
  color: white;
  font-size: 20px;
}
</style>
<div {#ic-push-url="true" ic-select-from-response="#page_content"#}>
{% if message %}
<div id="message">{{ message }}</div>
{% endif %}
{% if Street %}
    <div style="margin:10px;"><h3 style="color: white">Đường</h3>
  {% for item in Street %}
      <button class="btn btn-info info-street"
              ic-get-from="{% url 'bus_time:street_detail' item.slug %}"
              {# ic-get-from="{% url 'bus_time:streets' %}{{ item.slug }}" #}
              ic-target="#page_content">{{ item }}</button>
  {% endfor %}
    </div>
{% endif %}
{% if BusRoute %}
<div class="name-route" style="margin:10px;"><h3 style="color: white">Tuyến</h3>
{% for item in BusRoute %}
  <button class="btn btn-info info-route"
          ic-get-from="{# url 'wip' #}{% url 'bus_time:route_detail' item.external_id %}"
          ic-target="#page_content">{{ item.name }}</button>
{% endfor %}
</div>
{% endif %}
</div>

bus_time/templates/bus_time/street.html
{% load i18n %}
<style scoped="">
.tram_duong {
  margin:10px;padding-left:20px;padding-right:20px;border:1px solid;
}
.duong {
  padding:10px;
  border-top:2px solid;
  border-bottom:2px solid;
  background-color:rgba(255,255,255,0.8);
}
.duong_ve {
  padding:10px;
  border-top:2px solid;
  border-bottom:2px solid;
  background-color:rgba(255,99,71,0.8);
}
.ic-transitioning #Mh_Duong {
  background: darkseagreen;
}
#Mh_Duong {
  transition: all 3.0s;
}
</style>
{% load tz %}
{% get_current_timezone as TIME_ZONE %}
<div class="container-fluid w3-cell-row" id="details">
</div>
<div id="Mh_Duong">
  <div class="container-fluid w3-cell-row w3-center">
    {% include "bus_time/generic_street.html" with stops=even_stops %}
  </div>
  <div class="w3-container btn duong w3-row w3">
    <div class="btn w3-cell w3-col l4 m4 w3-center">
      {% for sor, end_div, sor_first in previous_sor %} {# TODO: order by route, direction, order #}
      {% ifchanged sor.bus_route %}<div class="row">{# of route row #}
        <!--div class="col street-inline"!-->
        <div class="col w3-container w3-cell w3-cell-middle">
          {% url 'bus_time:street_detail' sor_first.bus_stop.street.slug as get_from %}
          {% include "bus_time/generic_button.html" with get_from=get_from content=sor_first.bus_stop.street.name cls_type='street' target='page_content' %}
        </div>
        <div class="col w3-container w3-cell w3-cell-middle">
          {% url 'bus_time:route_detail' sor.bus_route.external_id as get_from %}
          {% include "bus_time/generic_button.html" with get_from=get_from content=sor.bus_route.external_id cls_type='route' target='page_content' %}
        </div>
        <div class="col w3-container w3-cell w3-cell-middle"> {% endifchanged %}
          {% url 'bus_time:street_detail' sor.bus_stop.street.slug as get_from %}
          {% include "bus_time/generic_button.html" with get_from=get_from content=sor.bus_stop.street.name cls_type='street' target='page_content' %}
        {% if end_div %}
        </div>
      </div>{% else %}<br/>{% endif %}
      {% empty %}&nbsp;
      {% endfor %}
    </div>
    <div class="btn w3-cell w3-col l4 m4 w3-text-blue w3-center">
      <h1 class="">{{ street.name }}</h1>
      <input type="hidden" id="object_with_id" name="object_with_id" value="street-{{ street.slug }}">
    </div>
    <div class="btn w3-cell w3-col l4 m4 w3-center">
      {% for sor, end_div, sor_last in next_sor %} {# TODO: order by route, direction, order #}
      {% ifchanged sor.bus_route %}<div class="row">
        <div class="col w3-container w3-cell w3-cell-middle">{% endifchanged %}
          {% url 'bus_time:street_detail' sor.bus_stop.street.slug as get_from %}
          {% include "bus_time/generic_button.html" with get_from=get_from content=sor.bus_stop.street.name cls_type='street' target='page_content' %}
        {% if end_div %}</div>
        <div class="col w3-container w3-cell w3-cell-middle">
          {% url 'bus_time:route_detail' sor.bus_route.external_id as get_from %}
          {% include "bus_time/generic_button.html" with get_from=get_from content=sor.bus_route.external_id cls_type='route' target='page_content' %}
        </div>
        <div class="col w3-container w3-cell w3-cell-middle">
          {% url 'bus_time:street_detail' sor_last.bus_stop.street.slug as get_from %}
          {% include "bus_time/generic_button.html" with get_from=get_from content=sor_last.bus_stop.street.name cls_type='street' target='page_content' %}
        </div>
      </div>{% else %}<br/>{% endif %}
      {% endfor %}
    </div>
  </div>
  {% if check_next %}
  {% else %}
  <div class="w3-container btn duong_ve w3-row w3">
    <div class="btn w3-cell w3-col l4 m4 w3-center">
      {% for sor, end_div, sor_first in previous_sor_odd %} {# TODO: order by route, direction, order #}
      {% ifchanged sor.bus_route %}<div class="row">{# of route row #}
        <!--div class="col street-inline"!-->
        <div class="col w3-container w3-cell w3-cell-middle">
          {% url 'bus_time:street_detail' sor_first.bus_stop.street.slug as get_from %}
          {% include "bus_time/generic_button.html" with get_from=get_from content=sor_first.bus_stop.street.name cls_type='street' target='page_content' %}
        </div>
        <div class="col w3-container w3-cell w3-cell-middle">
          {% url 'bus_time:route_detail' sor.bus_route.external_id as get_from %}
          {% include "bus_time/generic_button.html" with get_from=get_from content=sor.bus_route.external_id cls_type='route' target='page_content' %}
        </div>
        <div class="col w3-container w3-cell w3-cell-middle"> {% endifchanged %}
          {% url 'bus_time:street_detail' sor.bus_stop.street.slug as get_from %}
          {% include "bus_time/generic_button.html" with get_from=get_from content=sor.bus_stop.street.name cls_type='street' target='page_content' %}
        {% if end_div %}
        </div>
      </div>{% else %}<br/>{% endif %}
      {% empty %}&nbsp;
      {% endfor %}
    </div>
    <div class="btn w3-cell w3-col l4 m4 w3-text-blue w3-center">
      <h1>{{ street.name }}</h1>
    </div>
    <div class="btn w3-cell w3-col l4 m4 w3-center">
      {% for sor, end_div, sor_last in next_sor_odd %} {# TODO: order by route, direction, order #}
      {% ifchanged sor.bus_route %}<div class="row">
        <div class="col w3-container w3-cell w3-cell-middle">{% endifchanged %}
          {% url 'bus_time:street_detail' sor.bus_stop.street.slug as get_from %}
          {% include "bus_time/generic_button.html" with get_from=get_from content=sor.bus_stop.street.name cls_type='street' target='page_content' %}
        {% if end_div %}</div>
        <div class="col w3-container w3-cell w3-cell-middle">
          {% url 'bus_time:route_detail' sor.bus_route.external_id as get_from %}
          {% include "bus_time/generic_button.html" with get_from=get_from content=sor.bus_route.external_id cls_type='route' target='page_content' %}
        </div>
        <div class="col w3-container w3-cell w3-cell-middle">
          {% url 'bus_time:street_detail' sor_last.bus_stop.street.slug as get_from %}
          {% include "bus_time/generic_button.html" with get_from=get_from content=sor_last.bus_stop.street.name cls_type='street' target='page_content' %}
        </div>
      </div>{% else %}<br/>{% endif %}
      {% endfor %}
    </div>
  </div>
  {% endif %}
  <div class="container-fluid w3-cell-row w3-center">
    {% include "bus_time/generic_street.html" with stops=odd_stops %}
  </div>
</div>